import = [
    "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
]

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 600
