import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark_custom.toml"
]

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 550
blink_timeout = 0

[window]
decorations = "full"
dimensions = { columns = 81, lines = 24 }
dynamic_padding = true
dynamic_title = true
opacity = 0.8
